### ISSUE TITLE
Can you do something like this?

### ISSUE THREAD

**Issue by FlexShashlik** [MairwunNx/AnotherStorm#2]
I think, that if you can implement this theme your stars in this repo will increase in exponential progression.
![image](https://user-images.githubusercontent.com/19716892/68043112-9b04bc80-fce5-11e9-9ecd-6fd3594b2e2d.png)

**Comment by MairwunNx** [comment]
## @SevadaSahakyan This is true, I am far from **Designer Evgeniy**  :(
